name: Say Hello

on:
  push: 
    branches:
      - main

jobs: 
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        run: echo "Hola Jose"
      - name: Fecha
        run: date
      - name: Directorio actual
        run: pwd
